name: Android Appium CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    container:
      image: budtmo/docker-android-x86-11.0
      options: --privileged

    timeout-minutes: 30

    steps:
      - name: Checkout репозитория
        uses: actions/checkout@v3

      - name: Установка Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Установка зависимостей
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Ожидание запуска эмулятора и Appium
        run: |
          echo "Ожидание 60 секунд запуска эмулятора..."
          sleep 60
          adb devices
          curl http://localhost:4723/wd/hub/status

      - name: Запуск тестов
        run: pytest tests/ --maxfail=1 --disable-warnings
