name: Android Appium CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout репозитория
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t local-appium-image .

      - name: Запуск тестов
        run: |
          docker run --privileged \
            -v ${{ github.workspace }}:/app \
            -w /app \
            -e BASE_DIR="/app" \
            local-appium-image \
            bash -c "
              emulator -avd test -no-audio -no-window -no-boot-anim &
              adb wait-for-device &&
              nohup appium --base-path /wd/hub > appium.log 2>&1 &
              sleep 30 &&
              pytest tests/ --maxfail=1 --disable-warnings"
      
